### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by mitchellmebane** [dnicolson/Binary-Plist#11]
I see from the `package.json` that the extension is MIT-licensed.  However, that took a little bit of digging to find.  If you add a LICENSE file to the repo, it will be easier to find.  As a bonus, it looks like that will also make the license show up in the Marketplace page (https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-integration).

Thanks for making this extension!

**Comment by dnicolson** [comment]
Sorry for the delay, notifications were turned off for some reason. Version 0.6.0 is based on the newer extension structure and contains a LICENSE file. It's live on the Marketplace now, the license link doesn't appear yet though.
