### ISSUE TITLE
Non-ASCII characters can't display properly on Windows

### ISSUE THREAD

**Issue by TkzcM** [dnicolson/Binary-Plist#111]
![image](https://user-images.githubusercontent.com/45264418/172181902-c59f1f0d-33e6-4191-86f5-7ddc7bca5f95.png)
plist Editor Pro:
![image](https://user-images.githubusercontent.com/45264418/172182689-128d1668-c88c-4d76-bab5-e11e54e26c71.png)

**Comment by dnicolson** [comment]
Please try version 0.9.0 of the extension, it might fix your issue.

**Comment by TkzcM** [comment]
![image](https://user-images.githubusercontent.com/45264418/172752695-2012f89d-9c2d-4f6a-9b0e-bc83c5a994f3.png)

Thanks for your helping. But it's still not working.

**Comment by dnicolson** [comment]
What exactly is the problem in the screenshot? The `Title` values appear to be decoded properly now, unlike in the first screenshot.

**Comment by TkzcM** [comment]
The value is garbled text.
It seems like that the text was decoded with Unicode, got the U+FFFD characters, then encoded with GBK, which is 锟(0xEFBF), 斤(0xBDEF), 拷(0xBFBD).
The encoding of the plist file is GBK.

**Comment by dnicolson** [comment]
Can you provide a reduced example file?

**Comment by TkzcM** [comment]
https://anonfiles.com/pet2p6ofyb/device_carrier_46000_D79_46.0.2_plist

**Comment by TkzcM** [comment]
Sorry, I think I accidentally opened the plist file saved by v0.8.0. Other plist files works flawlessly.
Thanks a lot for your hard working!
