### ISSUE TITLE
Editor chooser: cannot open directly, need to keep selecting "Configure default..."

### ISSUE THREAD

**Issue by iandol** [dnicolson/Binary-Plist#112]
When opening a binary plist (and clicking open anayway), I get a requestor:

<img width="602" alt="Screenshot 2022-08-31 at 13 20 41" src="https://user-images.githubusercontent.com/153905/187677418-4beba5be-8d01-40a9-8f86-bb2949860b60.png">

If I select "Text Editor" only the binary view is opened. If I select "Configure default editor..." and then select "Text Editor" then both the binary and XML representations are opened. I have to do this each time I open the file.

macOS 12.5.1 VSCode 1.70.2 extension 0.9.1

**Comment by iandol** [comment]
Oh, this extension is super, thanks you so much for this!!!

**Comment by dnicolson** [comment]
The picker was introduced in version 1.56 and I don't think there is any way around it.

**Comment by dnicolson** [comment]
That functionality is from Visual Studio Code itself, so it's possible there's an issue there. This is how it is supposed to work:

![binary plist (1)](https://user-images.githubusercontent.com/2276355/187966539-c7d9f651-5d7b-463d-93db-7d1499768548.gif)

**Comment by iandol** [comment]
Hm, with the latest VSCode I now get this:

https://user-images.githubusercontent.com/153905/188171401-61cd7fa9-6cbe-472d-b924-7f29842d7b67.mp4

First open works but second doesn't. I have to close the window and create a new window, then it works again... :lol:

**Comment by dnicolson** [comment]
So the original issue is resolved? I am aware of the issue of reopening the same file twice in one session, I've been meaning to fix it but it's a little messy.

**Comment by dnicolson** [comment]
Please try version 0.10.0, it should resolve the issue. The relatively new tabGroups API is used, so version 1.67.2 or later of Visual Studio Code is also now required.

**Comment by iandol** [comment]
Yes, this seems to be working, thanks so much! I'll close this issue.
