### ISSUE TITLE
Another tab does not open

### ISSUE THREAD

**Issue by ghost** [dnicolson/Binary-Plist#113]
I don't get the "Do you want to open it anyway?" prompt, it just open the plist file straight forward without prompt and without opening another tab

I'm using VS code 1.77.1 on Windows 11 2H22

**Comment by dnicolson** [comment]
Can you provide a sample file?

Visual Studio Code also has slightly different prompts now, I will update the documentation.

**Comment by dnicolson** [comment]
Visual Studio Code opened the additional tab without any binary prompt.

<img width="1288" alt="Screenshot 2023-04-12 at 18 36 29" src="https://user-images.githubusercontent.com/2276355/231524615-bfd42579-1812-4de0-8f4c-5485137e877b.png">

**Comment by dnicolson** [comment]
What if you try version 1.77.2 without any other extensions enabled?
