### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by Mei-Lewis-Mei** [dnicolson/Binary-Plist#115]
I can't get it to open the xml tab in vscode on MacOS 13.3.1 and the lack of documentation or any videos or tutorials online about this piece of software suggests to me that some update to vscode or macos has made it fail.

Thanks

**Comment by dnicolson** [comment]
This is maintained, you can see the release information and documentation on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=dnicolson.binary-plist) page.

It appears as though there might be an issue with the 0.11.1 release from earlier this month, can you try installing version 0.11.0 using the "Install Another Version…" menu item?

**Comment by dnicolson** [comment]
There was a packaging issue with version 0.11.1, this has been resolved with version 0.11.2.
