### ISSUE TITLE
Which left tab?

### ISSUE THREAD

**Issue by G3NSVRV** [dnicolson/Binary-Plist#3]
[2019-10-21_21h38_32.zip](https://github.com/dnicolson/Binary-Plist/files/3753446/2019-10-21_21h38_32.zip)

**Comment by dnicolson** [comment]
The left tab is the binary tab, an additional text tab should have opened to the right.

What version of Windows and VSCode are you using?

**Comment by G3NSVRV** [comment]
![image](https://user-images.githubusercontent.com/11720535/67285365-c8fc2c80-f4ad-11e9-9694-e6fc18b15e63.png)

**Comment by dnicolson** [comment]
Fixed in https://github.com/dnicolson/Binary-Plist/commit/fa79576eba86a41d96c048bd7131b585181a47ab and released as version 0.2.1.

**Comment by G3NSVRV** [comment]
it works now, thanks man!

**Comment by TBugReporter** [comment]
I've always had this problem with your extension; for several years, I simply used an external tool to convert bin to XML, and pasted into VSC.  However, that other tool has stopped working for me, leading me to try this again - with the same results.

**Comment by TBugReporter** [comment]
<img width="466" height="369" alt="Image" src="https://github.com/user-attachments/assets/6886c094-d45a-468b-9c20-3571d28a14e8" />
