### ISSUE TITLE
File association

### ISSUE THREAD

**Issue by j040p3d20** [dnicolson/Binary-Plist#7]
After associating an extension `*.data` with type `plist` on a certain workspace, I would expect the extension to work on all `*.data` files in that workspace.

**Comment by dnicolson** [comment]
Visual Studio Code determines the language mode of the file. If the language mode is manually changed this could persist between sessions (and for files of the same extension) but that is beyond the scope of this extension.

Please try version 0.5.0 of the extension, setting the language mode to `plist` can be used for files without a `.plist` extension.

You can customize which file extensions should be recognized as `plist` files by using Visual Studio Code's [files.associations](https://code.visualstudio.com/docs/languages/identifiers). Adding this to the settings would enable `*.data` files to be read as binary property lists:

```
 "files.associations": {
​      "*.data": "plist"
  }
```

**Comment by j040p3d20** [comment]
works great, thank you.
